#!/bin/bash -e

lockit () {
  exec {lockfd}<>~/.lilac/.lock
  flock -n $lockfd || {
    echo "Waiting for lock to release..."
    flock $lockfd
  }
}

lockit
mkdir -p ~/.lilac/log

export TZ=Asia/Shanghai
export TERM=xterm
export PATH=$HOME/bin:$HOME/.local/bin:$PATH
export PYTHONPATH=$HOME/scripts/python/pylib

lilac "$@" > ~/.lilac/log/"$(date +'%Y-%m-%dT%H:%M:%S')" 2>&1
