#!/bin/bash -e

lockit () {
  exec {lockfd}<>~/.lilac/.lock
  flock -n $lockfd || {
    echo "Waiting for lock to release..."
    flock $lockfd
  }
}

lockit
mkdir -p ~/.lilac/log
lilac > ~/.lilac/log/$(date +'%Y-%m-%dT%H:%M:%S') 2>&1
