#!/usr/bin/env python3

import json
import urllib.request
import sys

template = '''\
_pkgname={name}
pkgname=python-{pkgname}
pkgver={version}
pkgrel=1
pkgdesc="{summary}"
arch=('any')
url="{home_page}"
license=('{license}')
depends=('python')
_name=${{pkgname#python-}}
source=("https://files.pythonhosted.org/packages/source/${_name::1}/${{_name}}/${{_name}}-${{pkgver}}.tar.gz")
md5sums=('{md5_digest}')

build() {{
  cd "$srcdir/$_pkgname-$pkgver"
  LANG=en_US.UTF-8 python3 setup.py build
}}

package() {{
  cd "$srcdir/$_pkgname-$pkgver"
  LANG=en_US.UTF-8 python3 setup.py install --root=$pkgdir --optimize=1 --skip-build
}}

# vim:set sw=2 et:
'''

def get_pkgbuild(j):
  info = j['info']
  try:
    info['license'] = info['license'].split()[0]
  except IndexError:
    info['license'] = '(FIXME)'
  release = [x for x in j['releases'][info['version']]
             if x['python_version'] == 'source'][-1]
  info.update(release)
  info['pkgname'] = info['name'].lower()
  s = template.format_map(info)
  return s

def get_json(name):
  url = 'https://pypi.org/pypi/%s/json' % name
  res = urllib.request.urlopen(url)
  data = res.read().decode('utf-8')
  j = json.loads(data)
  return j

def main():
  if len(sys.argv) != 2:
    sys.exit('PyPI package name?')
  name = sys.argv[1]
  j = get_json(name)
  pkg = get_pkgbuild(j)
  sys.stdout.write(pkg)

if __name__ == '__main__':
  main()
