#!/usr/bin/python3

from lilac2.tools import read_config
from lilac2.repo import Repo

def main():
  config = read_config()
  r = Repo(config)
  r.sendmail(YOUR_ADDRESS_HERE, 'test', 'This is a test mail.')

if __name__ == '__main__':
  main()

