#!/usr/bin/python3

import json
import sys

import yaml

def main():
  d = yaml.safe_load(sys.stdin)
  json.dump(d, sys.stdout, ensure_ascii=False, indent=2)
  print()

if __name__ == '__main__':
  main()

