#!/usr/bin/env python3

import json
import sys

import yamlutils

def main():
  d = yamlutils.load(sys.stdin)
  json.dump(d, sys.stdout, ensure_ascii=False, indent=2)

if __name__ == '__main__':
  main()

